"""Change db

Revision ID: ecff7ac752b7
Revises: 
Create Date: 2025-05-04 15:59:59.395215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecff7ac752b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=True))
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
